plugins {
    id 'java'
}

group 'pl.sapplayer'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    // Lokalny katalog dla plików JAR
    flatDir {
        dirs 'libs' // Wskazuje na katalog 'libs' w głównym folderze projektu
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    // Zależność dla biblioteki ASAP
    implementation 'net.sf.asap:asap' // Sprawdź najnowszą wersję na Maven Central, 4.1.0 jest aktualna
    // Do ikon i innych zasobów
    // testImplementation platform('org.junit:junit-bom:5.10.0')
    // testImplementation 'org.junit.jupiter:junit-jupiter'
}
// Dodatkowo, aby mieć pewność, że zasoby są pakowane prawidłowo (opcjonalne, ale dobre praktyki)
sourceSets {
    main {
        resources {
            srcDirs = ["src/main/resources"]
        }
    }
}

